### ISSUE TITLE
This function in this node can only be accessed from either the main thread or a thread group. Use call_deferred() instead.

### ISSUE THREAD

**Issue by andzejsp** [Jummit/godot-destruction-plugin#12]
Godot version: v4.1.1.stable.official [bd6af8e0e]
plugin: ( from release page the latest one)

Hello, im new to godot 4 and this plugin, great job, everything kinda works, but..

There are 2 things i cant understand:

1) Every time i trigger destroy() function the shards are loaded and it lags the game for a sec until shards get loaded or physics gets computed or whatever. Is there a way to mitigate this?

2) I get these errors in the debugger every time i call destroy()

```
E 0:00:04:0582   get_transform: This function in this node (CollisionShape) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  <C++ Error>    Condition "!is_readable_from_caller_thread()" is true. Returning: (Transform3D())
  <C++ Source>   scene/3d/node_3d.cpp:314 @ get_transform()

E 0:00:04:0583   get_position: This function in this node (OuterBox_frack_cell_003) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  <C++ Error>    Condition "!is_readable_from_caller_thread()" is true. Returning: (Vector3())
  <C++ Source>   scene/3d/node_3d.cpp:509 @ get_position()

```

these errors shows up for every mesh fragment i have in the broken.tscn 

My game setup:

![image](https://github.com/Jummit/godot-destruction-plugin/assets/80409979/46a484ee-3460-4f59-bd69-4b9a63ff58d3)

On timer event i generate my mesh - solid (ignore crate2_broken node)

![image](https://github.com/Jummit/godot-destruction-plugin/assets/80409979/1f5d851d-7623-400e-a7c6-725f325021b2)

For the crate-des-solid script:

```
# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	if Input.is_action_just_pressed("ui_accept"):
		explodeCrate.emit(true)
```

i have custom signal "explodeCrate" that is connected to Destruction node.

in Destruction node script:

```
func _on_cratedessolid_explode_crate(is_exploded):
	destroy()
	pass # Replace with function body.
```

Demo:
![Godot_v4 1 1-stable_win64_nmy89d4eiS](https://github.com/Jummit/godot-destruction-plugin/assets/80409979/d3b0671d-e8b6-4056-988b-ba20ed3f224d)

**Comment by Jummit** [comment]
This is fixed in the newest version by not using threads.
