### ISSUE TITLE
Doesn't follow scale

### ISSUE THREAD

**Issue by ZachAR3** [Jummit/godot-destruction-plugin#14]
Spawned shards don't follow the original objects scale. I looked at adding scale but due to your strange (it may be performant but I don't understand it haha) caching system the scales of objects are constantly reverted every frame for some reason? 

Here is the code I used in my C# version if you wanna figure it out yourself
```
var meshInstance = new MeshInstance3D
{
Mesh = shardMeshTyped.Mesh,
Scale = settings.Scale,
Name = "MeshInstance"
};
newShard.AddChild(meshInstance);

// Sets the shards collision shape to be a generation of the mesh instance with the given variables and adds it as a child.
var collisionShape = new CollisionShape3D
{
Shape = meshInstance.Mesh.CreateConvexShape(
	settings.CleanCollisionMesh,
	settings.SimplifyCollisionMesh),
Scale = settings.Scale,
Name = "CollisionShape"
};
```
and then I multiplied the position of each shard with 
`newShard.Position = shardMeshTyped.Position * settings.Scale;`
where settings.Scale is just the parents scale.

**Comment by Jummit** [comment]
Thanks for the report! Sorry to hear that the caching system is hard to understand. Instead of calling `instantiate` every time a destructible node is destroyed, I cache the result in a global dictionary.

**Comment by ZachAR3** [comment]
> Thanks for the report! Sorry to hear that the caching system is hard to understand. Instead of calling `instantiate` every time a destructible node is destroyed, I cache the result in a global dictionary.

No problem, I looked over it again and mostly get it now, but didn't feel like spending a lot of time debugging when I knew you could fix it much easier haha. Glad you got it worked out
