### ISSUE TITLE
Lag when large quantities of shards are spawned.

### ISSUE THREAD

**Issue by ZachAR3** [Jummit/godot-destruction-plugin#8]
Large lag spikes especially in models with complex shards when spawning larger amounts such as 100. I found this is due to the  generated collision meshes being far more complex than needed, which can be fixed by setting simplify to true, but this causes delay. Implementing a mesh-pre-gen system such as in the C# version I made [here](https://github.com/ZachAR3/Godot-Destruction-Plugin-CSharp) fixes this and allows Godot to easily handles over 100 objects without lag.

**Comment by Jummit** [comment]
I created this plugin mainly for prototyping and visual effects with a low quantity of objects. When it is used in performance-critical situations it should be extended and tailored to the need of the user, like you did. I pushed a patch to use threads to generate the shards nonetheless, thanks for the idea!
