### ISSUE TITLE
When setting collision layers, the names show 2d

### ISSUE THREAD

**Issue by ZachAR3** [Jummit/godot-destruction-plugin#9]
Heya, just noticed you used the @export_flags_2d_physics flag which causes it to look at 2D instead of 3D meaning the names don't show up. Super simple fix, I just don't feel like going through the hassle of making a PR for it haha.

**Comment by Jummit** [comment]
> Heya, just noticed you used the @export_flags_2d_physics flag which causes it to look at 2D instead of 3D meaning the names don't show up. Super simple fix, I just don't feel like going through the hassle of making a PR for it haha.

Nice catch.
